# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.episodes_api import EpisodesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEpisodesApi(unittest.TestCase):
    """EpisodesApi unit test stubs"""

    def setUp(self):
        self.api = EpisodesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_check_users_saved_episodes(self):
        """Test case for check_users_saved_episodes

        Check User's Saved Episodes   # noqa: E501
        """
        pass

    def test_get_a_shows_episodes(self):
        """Test case for get_a_shows_episodes

        Get Show Episodes   # noqa: E501
        """
        pass

    def test_get_an_episode(self):
        """Test case for get_an_episode

        Get Episode   # noqa: E501
        """
        pass

    def test_get_multiple_episodes(self):
        """Test case for get_multiple_episodes

        Get Several Episodes   # noqa: E501
        """
        pass

    def test_get_users_saved_episodes(self):
        """Test case for get_users_saved_episodes

        Get User's Saved Episodes   # noqa: E501
        """
        pass

    def test_remove_episodes_user(self):
        """Test case for remove_episodes_user

        Remove User's Saved Episodes   # noqa: E501
        """
        pass

    def test_save_episodes_user(self):
        """Test case for save_episodes_user

        Save Episodes for Current User   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
