# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CursorPagingObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'limit': 'int',
        'next': 'str',
        'cursors': 'AllOfCursorPagingObjectCursors',
        'total': 'int'
    }

    attribute_map = {
        'href': 'href',
        'limit': 'limit',
        'next': 'next',
        'cursors': 'cursors',
        'total': 'total'
    }

    def __init__(self, href=None, limit=None, next=None, cursors=None, total=None):  # noqa: E501
        """CursorPagingObject - a model defined in Swagger"""  # noqa: E501
        self._href = None
        self._limit = None
        self._next = None
        self._cursors = None
        self._total = None
        self.discriminator = None
        if href is not None:
            self.href = href
        if limit is not None:
            self.limit = limit
        if next is not None:
            self.next = next
        if cursors is not None:
            self.cursors = cursors
        if total is not None:
            self.total = total

    @property
    def href(self):
        """Gets the href of this CursorPagingObject.  # noqa: E501

        A link to the Web API endpoint returning the full result of the request.  # noqa: E501

        :return: The href of this CursorPagingObject.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this CursorPagingObject.

        A link to the Web API endpoint returning the full result of the request.  # noqa: E501

        :param href: The href of this CursorPagingObject.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def limit(self):
        """Gets the limit of this CursorPagingObject.  # noqa: E501

        The maximum number of items in the response (as set in the query or by default).  # noqa: E501

        :return: The limit of this CursorPagingObject.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this CursorPagingObject.

        The maximum number of items in the response (as set in the query or by default).  # noqa: E501

        :param limit: The limit of this CursorPagingObject.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def next(self):
        """Gets the next of this CursorPagingObject.  # noqa: E501

        URL to the next page of items. ( `null` if none)  # noqa: E501

        :return: The next of this CursorPagingObject.  # noqa: E501
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this CursorPagingObject.

        URL to the next page of items. ( `null` if none)  # noqa: E501

        :param next: The next of this CursorPagingObject.  # noqa: E501
        :type: str
        """

        self._next = next

    @property
    def cursors(self):
        """Gets the cursors of this CursorPagingObject.  # noqa: E501

        The cursors used to find the next set of items.  # noqa: E501

        :return: The cursors of this CursorPagingObject.  # noqa: E501
        :rtype: AllOfCursorPagingObjectCursors
        """
        return self._cursors

    @cursors.setter
    def cursors(self, cursors):
        """Sets the cursors of this CursorPagingObject.

        The cursors used to find the next set of items.  # noqa: E501

        :param cursors: The cursors of this CursorPagingObject.  # noqa: E501
        :type: AllOfCursorPagingObjectCursors
        """

        self._cursors = cursors

    @property
    def total(self):
        """Gets the total of this CursorPagingObject.  # noqa: E501

        The total number of items available to return.  # noqa: E501

        :return: The total of this CursorPagingObject.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this CursorPagingObject.

        The total number of items available to return.  # noqa: E501

        :param total: The total of this CursorPagingObject.  # noqa: E501
        :type: int
        """

        self._total = total

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CursorPagingObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CursorPagingObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
