# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExternalIdObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'isrc': 'str',
        'ean': 'str',
        'upc': 'str'
    }

    attribute_map = {
        'isrc': 'isrc',
        'ean': 'ean',
        'upc': 'upc'
    }

    def __init__(self, isrc=None, ean=None, upc=None):  # noqa: E501
        """ExternalIdObject - a model defined in Swagger"""  # noqa: E501
        self._isrc = None
        self._ean = None
        self._upc = None
        self.discriminator = None
        if isrc is not None:
            self.isrc = isrc
        if ean is not None:
            self.ean = ean
        if upc is not None:
            self.upc = upc

    @property
    def isrc(self):
        """Gets the isrc of this ExternalIdObject.  # noqa: E501

        [International Standard Recording Code](http://en.wikipedia.org/wiki/International_Standard_Recording_Code)   # noqa: E501

        :return: The isrc of this ExternalIdObject.  # noqa: E501
        :rtype: str
        """
        return self._isrc

    @isrc.setter
    def isrc(self, isrc):
        """Sets the isrc of this ExternalIdObject.

        [International Standard Recording Code](http://en.wikipedia.org/wiki/International_Standard_Recording_Code)   # noqa: E501

        :param isrc: The isrc of this ExternalIdObject.  # noqa: E501
        :type: str
        """

        self._isrc = isrc

    @property
    def ean(self):
        """Gets the ean of this ExternalIdObject.  # noqa: E501

        [International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29)   # noqa: E501

        :return: The ean of this ExternalIdObject.  # noqa: E501
        :rtype: str
        """
        return self._ean

    @ean.setter
    def ean(self, ean):
        """Sets the ean of this ExternalIdObject.

        [International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29)   # noqa: E501

        :param ean: The ean of this ExternalIdObject.  # noqa: E501
        :type: str
        """

        self._ean = ean

    @property
    def upc(self):
        """Gets the upc of this ExternalIdObject.  # noqa: E501

        [Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code)   # noqa: E501

        :return: The upc of this ExternalIdObject.  # noqa: E501
        :rtype: str
        """
        return self._upc

    @upc.setter
    def upc(self, upc):
        """Sets the upc of this ExternalIdObject.

        [Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code)   # noqa: E501

        :param upc: The upc of this ExternalIdObject.  # noqa: E501
        :type: str
        """

        self._upc = upc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalIdObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalIdObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
