# coding: utf-8

"""
    Spotify Web API

    You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PublicUserObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_name': 'str',
        'external_urls': 'AllOfPublicUserObjectExternalUrls',
        'followers': 'AllOfPublicUserObjectFollowers',
        'href': 'str',
        'id': 'str',
        'images': 'list[ImageObject]',
        'type': 'str',
        'uri': 'str'
    }

    attribute_map = {
        'display_name': 'display_name',
        'external_urls': 'external_urls',
        'followers': 'followers',
        'href': 'href',
        'id': 'id',
        'images': 'images',
        'type': 'type',
        'uri': 'uri'
    }

    def __init__(self, display_name=None, external_urls=None, followers=None, href=None, id=None, images=None, type=None, uri=None):  # noqa: E501
        """PublicUserObject - a model defined in Swagger"""  # noqa: E501
        self._display_name = None
        self._external_urls = None
        self._followers = None
        self._href = None
        self._id = None
        self._images = None
        self._type = None
        self._uri = None
        self.discriminator = None
        if display_name is not None:
            self.display_name = display_name
        if external_urls is not None:
            self.external_urls = external_urls
        if followers is not None:
            self.followers = followers
        if href is not None:
            self.href = href
        if id is not None:
            self.id = id
        if images is not None:
            self.images = images
        if type is not None:
            self.type = type
        if uri is not None:
            self.uri = uri

    @property
    def display_name(self):
        """Gets the display_name of this PublicUserObject.  # noqa: E501

        The name displayed on the user's profile. `null` if not available.   # noqa: E501

        :return: The display_name of this PublicUserObject.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this PublicUserObject.

        The name displayed on the user's profile. `null` if not available.   # noqa: E501

        :param display_name: The display_name of this PublicUserObject.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def external_urls(self):
        """Gets the external_urls of this PublicUserObject.  # noqa: E501

        Known public external URLs for this user.   # noqa: E501

        :return: The external_urls of this PublicUserObject.  # noqa: E501
        :rtype: AllOfPublicUserObjectExternalUrls
        """
        return self._external_urls

    @external_urls.setter
    def external_urls(self, external_urls):
        """Sets the external_urls of this PublicUserObject.

        Known public external URLs for this user.   # noqa: E501

        :param external_urls: The external_urls of this PublicUserObject.  # noqa: E501
        :type: AllOfPublicUserObjectExternalUrls
        """

        self._external_urls = external_urls

    @property
    def followers(self):
        """Gets the followers of this PublicUserObject.  # noqa: E501

        Information about the followers of this user.   # noqa: E501

        :return: The followers of this PublicUserObject.  # noqa: E501
        :rtype: AllOfPublicUserObjectFollowers
        """
        return self._followers

    @followers.setter
    def followers(self, followers):
        """Sets the followers of this PublicUserObject.

        Information about the followers of this user.   # noqa: E501

        :param followers: The followers of this PublicUserObject.  # noqa: E501
        :type: AllOfPublicUserObjectFollowers
        """

        self._followers = followers

    @property
    def href(self):
        """Gets the href of this PublicUserObject.  # noqa: E501

        A link to the Web API endpoint for this user.   # noqa: E501

        :return: The href of this PublicUserObject.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this PublicUserObject.

        A link to the Web API endpoint for this user.   # noqa: E501

        :param href: The href of this PublicUserObject.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def id(self):
        """Gets the id of this PublicUserObject.  # noqa: E501

        The [Spotify user ID](/documentation/web-api/concepts/spotify-uris-ids) for this user.   # noqa: E501

        :return: The id of this PublicUserObject.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PublicUserObject.

        The [Spotify user ID](/documentation/web-api/concepts/spotify-uris-ids) for this user.   # noqa: E501

        :param id: The id of this PublicUserObject.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def images(self):
        """Gets the images of this PublicUserObject.  # noqa: E501

        The user's profile image.   # noqa: E501

        :return: The images of this PublicUserObject.  # noqa: E501
        :rtype: list[ImageObject]
        """
        return self._images

    @images.setter
    def images(self, images):
        """Sets the images of this PublicUserObject.

        The user's profile image.   # noqa: E501

        :param images: The images of this PublicUserObject.  # noqa: E501
        :type: list[ImageObject]
        """

        self._images = images

    @property
    def type(self):
        """Gets the type of this PublicUserObject.  # noqa: E501

        The object type.   # noqa: E501

        :return: The type of this PublicUserObject.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PublicUserObject.

        The object type.   # noqa: E501

        :param type: The type of this PublicUserObject.  # noqa: E501
        :type: str
        """
        allowed_values = ["user"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def uri(self):
        """Gets the uri of this PublicUserObject.  # noqa: E501

        The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for this user.   # noqa: E501

        :return: The uri of this PublicUserObject.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this PublicUserObject.

        The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for this user.   # noqa: E501

        :param uri: The uri of this PublicUserObject.  # noqa: E501
        :type: str
        """

        self._uri = uri

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PublicUserObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PublicUserObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
